name: GeoTechCI

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_GeotechnicalTests
          MYSQL_USER: myuser
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build the JAR file
        run: mvn clean install
        working-directory: backend/database

      - name: Run tests
        run: mvn test
        working-directory: backend/database

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./backend/database/Dockerfile
          push: true
          tags: |
            ghcr.io/spe-uob/2024-geotechnicaltestingguidance:${{ github.sha }}
            ghcr.io/spe-uob/2024-geotechnicaltestingguidance:dev

